[versions]
dokka = "2.0.0"
kmpmt = "0.1.1"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
poko = "0.20.0"
publish = "0.36.0"

[libraries]
kotlin-test-core = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kmpmt = { id = "com.jakewharton.kmp-missing-targets", version.ref = "kmpmt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }