name: test

on:
  pull_request: {}
  push:
    branches:
      - 'trunk'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        job:
          - iosX64Test
          - jvmTest
          - linuxX64Test
          - macosArm64Test
          - macosX64Test
          - mingwX64Test
          - tvosSimulatorArm64Test
          - tvosX64Test
          - watchosSimulatorArm64Test
          - watchosX64Test
        exclude:
          - os: macOS-latest
            job:
              - linuxX64Test
              - mingwX64Test
          - os: windows-latest
            job:
              - iosX64Test
              - macosArm64Test
              - macosX64Test
              - mingwX64Test
              - tvosSimulatorArm64Test
              - tvosX64Test
              - watchosSimulatorArm64Test
              - watchosX64Test
          - os: ubuntu-latest
            job:
              - iosX64Test
              - macosArm64Test
              - macosX64Test
              - mingwX64Test
              - tvosSimulatorArm64Test
              - tvosX64Test
              - watchosSimulatorArm64Test
              - watchosX64Test

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: 19

      - run: ./gradlew ${{matrix.job}}