name: test

on:
  pull_request: {}
  push:
    branches:
      - 'trunk'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        job: [jvmTest]
        include:
          - os: macOS-latest
            job: iosX64Test
          - os: macOS-latest
            job: jvmTest
          - os: macOS-latest
            job: macosArm64Test
          - os: macOS-latest
            job: macosX64Test
          - os: macOS-latest
            job: tvosSimulatorArm64Test
          - os: macOS-latest
            job: tvosX64Test
          - os: macOS-latest
            job: watchosSimulatorArm64Test
          - os: macOS-latest
            job: watchosX64Test
          - os: windows-latest
            job: jvmTest
          - os: windows-latest
            job: mingwX64Test
          - os: ubuntu-latest
            job: jvmTest
          - os: ubuntu-latest
            job: linuxX64Test

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: 19

      - run: ./gradlew ${{matrix.job}}